server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:eventhub_db}
    username: ${POSTGRES_USER:rejouan}
    password: ${POSTGRES_PASSWORD:rejouan953}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
